version: "3.4"
services:
  botticelli_plugin:
    container_name: botticelli_plugin
    image: botticelli_plugin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      BASEROW_PUBLIC_URL: http://localhost
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data: